name: Create docker images

on: [create]

jobs:
  build:
    name: Build, push, and deploy
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build the theme Docker Image
        run: |
          docker build . --tag ghcr.io/letterpad/lp-theme:latest
          docker run ghcr.io/letterpad/lp-theme:latest
          docker push ghcr.io/letterpad/lp-theme:latest
